### ISSUE TITLE
Make it stable

### ISSUE THREAD

**Issue by laxhya-godara** [snehilrx/Fetch#77]
The app is really good but it needs more stability. Also maybe put a contact link in the app's settings

**Comment by snehilrx** [comment]
Absolutely, I'm actively addressing these concerns. Unfortunately, my daytime commitments have limited the time I can devote to fixing these issues. Nevertheless, the latest release has successfully addressed several major crashes!

**Comment by snehilrx** [comment]
Closing this issue, if you are still having issue we can reopen it later
